### ISSUE TITLE
Crash at the start

### ISSUE THREAD

**Issue by Cr1t-GYM** [RiS3-Lab/DICE-DMA-Emulation#3]
I followed the step in "https://github.com/RiS3-Lab/p2im/blob/master/docs/add_mcu.md" to add mcu stm32f103xe. You could see the mcu details the following.
FLASH_BASE_ADDR: 0x08000000
FLASH_SIZE: 512
RAM_BASE_ADDR: 0x20000000
RAM_SIZE: 64

Then I configured the stm32f103xe.cfg file and imported object.elf to the specific path. However, when I ran the fuzz.py, it crashed with the input test cases. I turned to my input data and found some documents like "model-depth:10, stage:1.0.json" and "depth: 9, stage: 2.0". It seems that it initialized successfully but cannot start the test cases.

Do you have any idea with this problem? Thanks for your prompt attention.

Sincerely,
Cr1t

**Comment by Cr1t-GYM** [comment]
btw, does the tool only support *.elf for binary input? Does it support *.axf for binary support?

**Comment by alejoseb** [comment]
First you have to verify that standard P2IM framework can extract the firmware model for your stm32f103xe, if that works correctly  and you get the model (json file), then you have to follow the procedure to verify why it is crashing (https://github.com/RiS3-Lab/p2im#analyzing-crashinghanging-input). Also remember that we do not provide ground truth for that specific MCU, you can duplicate the F103 included in the repository.

Which IDE are you using? I believe the *.axf is just an *elf file with a different extension for some STM32 IDEs, I mean this is valid only in this particular case, so you can just change the extension or just use them directly.

**Comment by Cr1t-GYM** [comment]
1. You're right. P2IM did extract the firmware model and I got json file. However, the extracting status is unstoppable. The example output in command line follows.
`
0.input.data.5
run f/w w/ seed input to check if there is aup
cmd_qemu: /home/gongyiming/DICE-DMA-Emulation/p2im/qemu/src/install/debian64/qemu/bin/qemu-system-gnuarmeclipse -nographic -aflFile /home/gongyiming/FuzzBase/Huida/1.0/inputs/input.data -board stm32f103xe-mcu stm32f103xe-image /home/gongyiming/DICE-DMA-Emulation/DICE-Evaluation/ARM/Fuzzing/Firmware/Binaries/stm32f103xe_hello_world.axf -pm-stage 3 -model-input /home/gongyiming/FuzzBase/Huida/1.0/0.input.data.4/peripheral_model.json -me-bin /home/gongyiming/DICE-DMA-Emulation/DICE-Evaluation/ARM/DICE-P2IM-Utilities/me.py -me-config mi-stm32f103xe.cfg

There is aup, run ME
cmd_me: /home/gongyiming/DICE-DMA-Emulation/DICE-Evaluation/ARM/DICE-P2IM-Utilities/me.py -c mi-stm32f103xe.cfg --run-num 0.input.data.5 --print-to-file --run-from-forkserver --afl-file /home/gongyiming/FuzzBase/Huida/1.0/inputs/input.data --model-if /home/gongyiming/FuzzBase/Huida/1.0/0.input.data.4/peripheral_model.json
***************
/home/gongyiming/DICE-DMA-Emulation/DICE-Evaluation/ARM/Fuzzing/Firmware/Binaries/stm32f103xe_hello_world.axf
***************
Change working dir to: 0.input.data.5/
CWD: /home/gongyiming/FuzzBase/Huida/1.0/0.input.data.5
Redirect stdout to file named stdout
Traceback (most recent call last):
  File "/home/gongyiming/DICE-DMA-Emulation/DICE-Evaluation/ARM/DICE-P2IM-Utilities/me.py", line 1158, in <module>
    ret_val = stage1()
  File "/home/gongyiming/DICE-DMA-Emulation/DICE-Evaluation/ARM/DICE-P2IM-Utilities/me.py", line 358, in stage1
    ret_val = qemu_run(cmd, cfg.retry_num, stage)
  File "/home/gongyiming/DICE-DMA-Emulation/DICE-Evaluation/ARM/DICE-P2IM-Utilities/me.py", line 192, in qemu_run
    color_print(error_rv[stage][ret_val], "red")
KeyError: 1
`
Therefore, I used KeyboardInterrupt to stop the fuzz.py manually. I looked up the json files and they were valid. Then I chose to start the afl_fuzz via the following cmd input as the fuzz.py had to be stopped manually.
`
/home/gongyiming/DICE-DMA-Emulation/p2im/afl/afl-fuzz -i /home/gongyiming/FuzzBase/Huida/1.0/inputs -o /home/gongyiming/FuzzBase/Huida/1.0/outputs -t 2000+ -QQ -a /home/gongyiming/DICE-DMA-Emulation/DICE-Evaluation/ARM/DICE-P2IM-Utilities/me.py -b mi-stm32f103xe.cfg -c /home/gongyiming/FuzzBase/Huida/1.0/0.input.data.5/peripheral_model.json -T Huida_1.0 -d /home/gongyiming/DICE-DMA-Emulation/p2im/qemu/src/install/debian64/qemu/bin/qemu-system-gnuarmeclipse -nographic -board stm32f103xe -mcu stm32f103xe -image /home/gongyiming/DICE-DMA-Emulation/DICE-Evaluation/ARM/Fuzzing/Firmware/Binaries/stm32f103xe_hello_world.axf -pm-stage 3 -aflFile @@
`
Then afl_fuzz crashed at the start. I believe this crash is different from the crash which resulted from the test queue.
`
afl-fuzz 2.06b by <lcamtuf@google.com>
[+] You have 32 CPU cores and 4 runnable tasks (utilization: 12%).
[+] Try parallel jobs - see docs/parallel_fuzzing.txt.
[*] Checking core_pattern...
[*] Checking CPU scaling governor...
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning '/home/gongyiming/FuzzBase/Huida/1.0/inputs'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] Attempting dry run with 'id:000000,orig:input.data'...
[*] Spinning up the fork server...

[-] Whoops, the target binary crashed suddenly, before receiving any input
    from the fuzzer! There are several probable explanations:

    - The current memory limit (2.00 GB) is too restrictive, causing the
      target to hit an OOM condition in the dynamic linker. Try bumping up
      the limit with the -m setting in the command line. A simple way confirm
      this diagnosis would be:

      ( ulimit -Sv $[2047 << 10]; /path/to/fuzzed_app )

      Tip: you can use http://jwilk.net/software/recidivm to quickly
      estimate the required amount of virtual memory for the binary.

    - The binary is just buggy and explodes entirely on its own. If so, you
      need to fix the underlying problem or find a better replacement.

    - Less likely, there is a horrible bug in the fuzzer. If other options
      fail, poke <lcamtuf@coredump.cx> for troubleshooting tips.

[-] PROGRAM ABORT : Fork server crashed with signal 11
         Location : init_forkserver(), afl-fuzz.c:2080

`
2. I usaully use Keil and MCUXpresso to write codes. They both use ARM CC to compile the codes and output the axf file to debug the codes. As far as I know, ARM GCC compiler will output elf file. The functions of these two file are the same

**Comment by Cr1t-GYM** [comment]
1. You're right. P2IM did extract the firmware model and I got json file. However, the extracting status is unstoppable. The example output in command line follows.

```
0.input.data.5
run f/w w/ seed input to check if there is aup
cmd_qemu: /home/gongyiming/DICE-DMA-Emulation/p2im/qemu/src/install/debian64/qemu/bin/qemu-system-gnuarmeclipse -nographic -aflFile /home/gongyiming/FuzzBase/Huida/1.0/inputs/input.data -board stm32f103xe-mcu stm32f103xe-image /home/gongyiming/DICE-DMA-Emulation/DICE-Evaluation/ARM/Fuzzing/Firmware/Binaries/stm32f103xe_hello_world.axf -pm-stage 3 -model-input /home/gongyiming/FuzzBase/Huida/1.0/0.input.data.4/peripheral_model.json -me-bin /home/gongyiming/DICE-DMA-Emulation/DICE-Evaluation/ARM/DICE-P2IM-Utilities/me.py -me-config mi-stm32f103xe.cfg

There is aup, run ME
cmd_me: /home/gongyiming/DICE-DMA-Emulation/DICE-Evaluation/ARM/DICE-P2IM-Utilities/me.py -c mi-stm32f103xe.cfg --run-num 0.input.data.5 --print-to-file --run-from-forkserver --afl-file /home/gongyiming/FuzzBase/Huida/1.0/inputs/input.data --model-if /home/gongyiming/FuzzBase/Huida/1.0/0.input.data.4/peripheral_model.json
***************
/home/gongyiming/DICE-DMA-Emulation/DICE-Evaluation/ARM/Fuzzing/Firmware/Binaries/stm32f103xe_hello_world.axf
***************
Change working dir to: 0.input.data.5/
CWD: /home/gongyiming/FuzzBase/Huida/1.0/0.input.data.5
Redirect stdout to file named stdout
Traceback (most recent call last):
  File "/home/gongyiming/DICE-DMA-Emulation/DICE-Evaluation/ARM/DICE-P2IM-Utilities/me.py", line 1158, in <module>
    ret_val = stage1()
  File "/home/gongyiming/DICE-DMA-Emulation/DICE-Evaluation/ARM/DICE-P2IM-Utilities/me.py", line 358, in stage1
    ret_val = qemu_run(cmd, cfg.retry_num, stage)
  File "/home/gongyiming/DICE-DMA-Emulation/DICE-Evaluation/ARM/DICE-P2IM-Utilities/me.py", line 192, in qemu_run
    color_print(error_rv[stage][ret_val], "red")
KeyError: 1
```

Therefore, I used KeyboardInterrupt to stop the fuzz.py manually. I looked up the json files and they were valid. Then I chose to start the afl_fuzz via the following cmd input as the fuzz.py had to be stopped manually.

```
/home/gongyiming/DICE-DMA-Emulation/p2im/afl/afl-fuzz -i /home/gongyiming/FuzzBase/Huida/1.0/inputs -o /home/gongyiming/FuzzBase/Huida/1.0/outputs -t 2000+ -QQ -a /home/gongyiming/DICE-DMA-Emulation/DICE-Evaluation/ARM/DICE-P2IM-Utilities/me.py -b mi-stm32f103xe.cfg -c /home/gongyiming/FuzzBase/Huida/1.0/0.input.data.5/peripheral_model.json -T Huida_1.0 -d /home/gongyiming/DICE-DMA-Emulation/p2im/qemu/src/install/debian64/qemu/bin/qemu-system-gnuarmeclipse -nographic -board stm32f103xe -mcu stm32f103xe -image /home/gongyiming/DICE-DMA-Emulation/DICE-Evaluation/ARM/Fuzzing/Firmware/Binaries/stm32f103xe_hello_world.axf -pm-stage 3 -aflFile @@
```

Then afl_fuzz crashed at the start. I believe this crash is different from the crash which resulted from the test queue.

```
afl-fuzz 2.06b by <lcamtuf@google.com>
[+] You have 32 CPU cores and 4 runnable tasks (utilization: 12%).
[+] Try parallel jobs - see docs/parallel_fuzzing.txt.
[*] Checking core_pattern...
[*] Checking CPU scaling governor...
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning '/home/gongyiming/FuzzBase/Huida/1.0/inputs'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Validating target binary...
[*] Attempting dry run with 'id:000000,orig:input.data'...
[*] Spinning up the fork server...

[-] Whoops, the target binary crashed suddenly, before receiving any input
    from the fuzzer! There are several probable explanations:

    - The current memory limit (2.00 GB) is too restrictive, causing the
      target to hit an OOM condition in the dynamic linker. Try bumping up
      the limit with the -m setting in the command line. A simple way confirm
      this diagnosis would be:

      ( ulimit -Sv $[2047 << 10]; /path/to/fuzzed_app )

      Tip: you can use http://jwilk.net/software/recidivm to quickly
      estimate the required amount of virtual memory for the binary.

    - The binary is just buggy and explodes entirely on its own. If so, you
      need to fix the underlying problem or find a better replacement.

    - Less likely, there is a horrible bug in the fuzzer. If other options
      fail, poke <lcamtuf@coredump.cx> for troubleshooting tips.

[-] PROGRAM ABORT : Fork server crashed with signal 11
         Location : init_forkserver(), afl-fuzz.c:2080
```

2. I usaully use Keil and MCUXpresso to write codes. They both use ARM CC to compile the codes and output the axf file to debug the codes. As far as I know, ARM GCC compiler will output elf file. The functions of these two file are the same.

**Comment by Cr1t-GYM** [comment]
> First you have to verify that standard P2IM framework can extract the firmware model for your stm32f103xe, if that works correctly and you get the model (json file), then you have to follow the procedure to verify why it is crashing (https://github.com/RiS3-Lab/p2im#analyzing-crashinghanging-input). Also remember that we do not provide ground truth for that specific MCU, you can duplicate the F103 included in the repository.
> 
> Which IDE are you using? I believe the *.axf is just an *elf file with a different extension for some STM32 IDEs, I mean this is valid only in this particular case, so you can just chance the extension.

Current fuzz.py for DICE-DMA-Emulation doesn't output run_fw.py automatically. Do I have to write it on my own?

**Comment by alejoseb** [comment]
>     1. extracting status is unstoppable

That is actually a wrong behavior. It has to finish automatically after P2IM does not observe more unknown interfaces (peripherals) or no new execution paths are observed. If the process does not finish automatically, it could be because P2IM identified too many SR (status registers) conditions in the same function space (4 or more), in that case it will spawn too many workers and eventually will not extract the correct model, the json file will be incomplete if you stop the process. You have more details in P2IM paper about the conditions to finish the extraction process, and also about P2IM limitations. 

Specifically, I have observed this issue in STM32 initialization code of some peripherals (ADC and others). In this case the driver has lots of empty "if" conditions that the developer is supposed to use and add code or ignore, but the conditions are there and makes P2IM to fail. I commented out the empty "if" statements and P2IM was able to extract the model.

We did our development and testing with GCC, and yes MCUXpresso rename the elf to axf, so you can safely interchange them. I cannot confirm that for other tools. I can give you just very little or no support if you use Keil or any other toolchain.

I recommend you to start with a very simple firmware (very few peripherals and no DMA at all) just to verify your whole setup. Then scale up considering the limitations described in P2IM and DICE papers. Also, double check the firmware preparation described in P2IM for fuzz testing.

> Current fuzz.py for DICE-DMA-Emulation doesn't output run_fw.py automatically. Do I have to write it on my own?

yes you have, both scripts are slightly different and QEMU patched with DICE have some extra parameters. You have plenty of
examples and configuration files to figure it out.
